server:
  port: 8080

mksmqtt:
  url: tcp://ztemq.battery-doctor.cn:1883
  topic: MS/C


spring:
  datasource:
    url: jdbc:mysql://192.168.3.137:3306/mks_mqtt?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: test
    password: mks123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  data:
    mongodb:
      database: iems
      host: 192.168.3.137
      port: 27017

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0